Heavily borrowed from http://cs231n.github.io/python-numpy-tutorial/

# Hello World

In [1]:
print("Hello World!")

Hello World!


In [2]:
print("Hello " + "World!")

Hello World!


In [3]:
print("Hello " + "World! " + str(42))

Hello World! 42


# Integers

Like other programming languages, Python has very good support for integers

In [2]:
x = 3
print(type(x))

<class 'int'>


In [3]:
print(x)

3


In [4]:
# Operations
print("+: " + str(x + 1))
print("-: " + str(x - 1))
print("*: " + str(x * 2))
print("/: " + str(x / 2))
print("//:" + str(x // 2))
print("**: " + str(x ** 2))

+: 4
-: 2
*: 6
/: 1.5
//:1
**: 9


In [5]:
# Storthands
x += 1
x = x + 1
print(x)

5


In [6]:
x *= 2
print(x)

10


In [9]:
x++ # Not valid python!

SyntaxError: invalid syntax (<ipython-input-9-9ee7c0f3109e>, line 1)

# Floats

In [7]:
y = 3.0
print(type(y))

<class 'float'>


In [8]:
print("/: " + str(y/2))

/: 1.5


# Booleans

In [9]:
t = True
f = False
print(type(t))
print(type(f))

<class 'bool'>
<class 'bool'>


In [10]:
print(t and f)

False


In [11]:
print(t or f)

True


In [12]:
print(not f)

True


# Strings

In [16]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)

hello


In [17]:
print(len(hello))

5


In [18]:
hw = hello + ' ' + world
print(hw)

hello world


C-style string formatting is also supported in Python!

In [19]:
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)
print("Some float: %0.2f"%(32.1313131))

hello world 12
Some float: 32.13


# Array

In [17]:
arr = [3, 1, 2, 4, 5]
print(type(arr))
print(arr)
print(len(arr))

<class 'list'>
[3, 1, 2, 4, 5]
5


In [14]:
print(arr[2])

2


In [18]:
print(arr[-1]) # Reverse indexing!
print(arr[-2])

5
4


In [19]:
print(arr[-10]) # Limits still apply!

IndexError: list index out of range

In [20]:
arr[2] = 'foo' 
print(arr)

[3, 1, 'foo', 4, 5]


In [21]:
arr.append('bar')
print(arr)

[3, 1, 'foo', 4, 5, 'bar']


In [22]:
last_element = arr.pop()
print(arr)
print(last_element)

[3, 1, 'foo', 4, 5]
bar


In [27]:
nums = [0, 1, 2, 3, 4]
print(nums)

[0, 1, 2, 3, 4]


In [28]:
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive)

[2, 3]


In [29]:
print(nums[2:])           # Get a slice from index 2 to the end
print(nums[:2])           # Get a slice from the start to index 2 (exclusive)

[2, 3, 4]
[0, 1]


In [30]:
# .... Get all elements except the last element
print(nums[:-1])

[0, 1, 2, 3]


In [31]:
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)

[0, 1, 8, 9, 4]


# Loops

In [32]:
for i in [0, 1, 2, 3, 4]:
    print(i)

0
1
2
3
4


In [33]:
# .... Better way to do this?
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [34]:
for language in ['english', 'german', 'arabic']:
    print(language)

english
german
arabic


You can also use `enumerate` to get `index`, `data` pairs

In [35]:
for language_index, language in enumerate(['english', 'german', 'arabic']):
    print(str(language_index) + ": " + language)

0: english
1: german
2: arabic


# List comprehensions!

In [36]:
some_list = [1,2,3,4,5]

squares_list = []
for num in some_list:
    squares_list.append(num ** 2)

print(some_list)
print(squares_list)

[1, 2, 3, 4, 5]
[1, 4, 9, 16, 25]


In [37]:
squares_list = [num ** 2 for num in some_list]

print(squares_list)

[1, 4, 9, 16, 25]


List comprehensions are extermely useful for writing concise code, and slightly more efficient as well!

In [38]:
some_list = [1,2,3,4,5]
other_list = [n * 2 + 5 + n * n * 3 for n in some_list]
print(other_list)

[10, 21, 38, 61, 90]


In [133]:
some_list = [1,2,3,4,5]
even_squares = [num ** 2 for num in some_list if num % 2 == 0]
print(even_squares)

[4, 16]


# Dictionaries

In [39]:
d = {'cat': 'cute', 'dog': 'furry'}
print(type(d))
print(d)

<class 'dict'>
{'cat': 'cute', 'dog': 'furry'}


In [40]:
print(d['cat'])

cute


In [41]:
print('cat' in d)

True


In [42]:
print('horse' in d)

False


In [43]:
d['horse'] = 'fast'
print(d)

{'cat': 'cute', 'dog': 'furry', 'horse': 'fast'}


In [44]:
# Looping
for animal in d:
    print('key: ' + str(animal))
    print('value: ' + str(d[animal]))

cat
cute
dog
furry
horse
fast


You get a `KeyError` if the key does not exist in the dictionary

In [45]:
d['duisburg']

KeyError: 'duisburg'

You can use the `.get` function to also specify a default value

In [47]:
print(d.get('duisburg', "DEFAULT_VALUE"))
print(d.get('cat', "DEFAULT_VALUE"))

DEFAULT_VALUE
cute


In [48]:
# This is quite useful, for example if you are maintaining a count of 
# tokens
token = 'duisburg'
d[token] = 1 + d.get(token, 0)
print(d[token])
d[token] = 1 + d.get(token, 0)
print(d[token])

# The above code increments the existing value if one exists, or just
# starts at 0

1
2


In [49]:
# Dictionary comprehensions
nums = [0, 1, 2, 3, 4]
even_num_to_square = {nums[x]: x for x in nums}
print(even_num_to_square)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4}


# Sets

In [50]:
cities = {'New York', 'Berlin', 'London'}
print(type(cities))
print(cities)

<class 'set'>
{'New York', 'London', 'Berlin'}


In [51]:
print('London' in cities)

True


In [52]:
print('Dusseldorf' in cities)

False


In [53]:
print(len(cities))

3


In [54]:
cities.add('Dusseldorf')
print(cities)

{'New York', 'London', 'Dusseldorf', 'Berlin'}


In [ ]:
cities.add('London')
print(cities)

In [55]:
cities.remove('Berlin')
print(cities)

{'New York', 'London', 'Dusseldorf'}


# Tuples

In [150]:
t = ('element_1', 'element_2')
print(type(t))
print(t)

<class 'tuple'>
('element_1', 'element_2')


In [56]:
t[0] = 'hello'

TypeError: 'bool' object does not support item assignment

In [57]:
some_dict = dict()
some_dict[t] = 5
print(some_dict)

{True: 5}


In [153]:
some_dict[['a', 'list']] = 10

TypeError: unhashable type: 'list'

# Functions

In [58]:
def sign(x):
    if x < 0:
        return 'negative'
    else:
        return 'positive'

for x in [-3, 2, 1]:
    print(sign(x))

negative
positive
positive


In [59]:
def sign(x, return_long=False):
    if x < 0:
        if return_long:
            return 'input is a negative number'
        else:
            return 'negative'
    else:
        if return_long:
            return 'input is a positive number'
        else:
            return 'positive'

for x in [-3, 2, 1]:
    print(sign(x))

negative
positive
positive


In [60]:
for x in [-3, 2, 1]:
    print(sign(x, return_long=True))

input is a negative number
input is a positive number
input is a positive number


____

# Numpy

In [23]:
import numpy as np

vector = np.array([1, 2, 3])
print(type(vector))
print(vector)

ModuleNotFoundError: No module named 'numpy'

In [63]:
print(vector.shape)

(3,)


In [64]:
print(vector[2])

3


In [65]:
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])
print(type(matrix))
print(matrix)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
print(matrix.shape)

(3, 3)


In [67]:
print(matrix[1])

[4 5 6]


In [70]:
print(np.zeros((5,3)))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [71]:
print(np.ones((5,3)))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [72]:
print(np.random.random((5,3)))

[[ 0.61747253  0.09219967  0.11859914]
 [ 0.79462848  0.82343262  0.39327561]
 [ 0.71669827  0.82834978  0.95759217]
 [ 0.70556144  0.71706935  0.23312   ]
 [ 0.08408179  0.27628312  0.61579356]]


## Numpy Array Indexing

In [73]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
print(a[0,1])

2


In [77]:
b = a[:2, 1:3]
print(b)

[[50  3]
 [ 6  7]]


In [78]:
b[0,0] = 50
print(b)

[[50  3]
 [ 6  7]]


In [79]:
print(a)

[[ 1 50  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [80]:
# ... Select second row of a ...

## Integer Array Indexing

In [100]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [101]:
print(np.array([a[0,1], a[2,1], a[1,0]]))

[2 6 3]


In [102]:
print(a[[0,2,1], [1,1,0]])

[2 6 3]


In [103]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [104]:
b = np.array([0, 2, 0, 1])

In [107]:
for i in range(a.shape[0]):
    a[i, b[i]] = 0
print(a)

[[ 0  2  3]
 [ 4  5  0]
 [ 0  8  9]
 [10  0 12]]


In [108]:
a[[0, 1, 2, 3], b] = 50
print(a)

[[50  2  3]
 [ 4  5 50]
 [50  8  9]
 [10 50 12]]


In [109]:
a[range(a.shape[0]), b] = 100
print(a)

[[100   2   3]
 [  4   5 100]
 [100   8   9]
 [ 10 100  12]]


## Boolean Indexing

In [110]:
a = np.random.random((5,3))
print(a)

[[ 0.1076366   0.97156687  0.95235352]
 [ 0.15022886  0.68271266  0.94210183]
 [ 0.24855577  0.77161264  0.1709077 ]
 [ 0.49779694  0.63213529  0.16590931]
 [ 0.25010788  0.45509489  0.02323678]]


In [112]:
result = []
for r in range(a.shape[0]):
    for c in range(a.shape[1]):
        if a[r,c] > 0.5:
            result.append(a[r,c])
print(np.array(result))

[ 0.97156687  0.95235352  0.68271266  0.94210183  0.77161264  0.63213529]


In [113]:
print(a[a>0.5])

[ 0.97156687  0.95235352  0.68271266  0.94210183  0.77161264  0.63213529]


In [114]:
print(a>0.5)

[[False  True  True]
 [False  True  True]
 [False  True False]
 [False  True False]
 [False False False]]


# Array Math

In [83]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(y)

[[ 5.  6.]
 [ 7.  8.]]


In [116]:
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [84]:
print(x * y)

[[  5.  12.]
 [ 21.  32.]]


In [85]:
print(x / y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [86]:
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [87]:
print(np.dot(x,y))

[[ 19.  22.]
 [ 43.  50.]]


# Numpy utility functions

In [90]:
a = np.arange(11)
print(a)
print(np.sum(a))
print(np.argmax(a))


[ 0  1  2  3  4  5  6  7  8  9 10]
55
10


In [92]:
a = np.random.random((5,2))
print("Matrix")
print(a)
print("Full sum: %0.2f "%(np.sum(a)))
print("Add across rows: ")
print(np.sum(a, axis=0))
print("Add across columns: ")
print(np.sum(a, axis=1))

Matrix
[[ 0.72881095  0.39522754]
 [ 0.04140909  0.88320723]
 [ 0.55553567  0.16173529]
 [ 0.88850153  0.61362696]
 [ 0.62931811  0.79636267]]
Full sum: 5.69 
Add across rows: 
[ 2.84357536  2.8501597 ]
Add across columns: 
[ 1.12403849  0.92461633  0.71727096  1.50212849  1.42568079]


# Broadcasting

In [93]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.zeros_like(x)

In [94]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [95]:
print(v)

[1 0 1]


In [96]:
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [97]:
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [126]:
# The above operation is the same as:

# [[ 1  2  3]          [[ 1  0  1]
#  [ 4  5  6]     +     [ 1  0  1]
#  [ 7  8  9]           [ 1  0  1]
#  [10 11 12]]          [ 1  0  1]]

In [98]:
y_broadcast = np.zeros_like(x)
print(x)
print(v)
y_broadcast = x + v
print(y_broadcast)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [99]:
import time
start_time = time.time()

for i in range(500000):
    y = np.zeros_like(x)
    for i in range(4):
        y[i, :] = x[i, :] + v

end_time = time.time()
print(end_time-start_time)

4.028761148452759


In [100]:
start_time = time.time()

for i in range(500000):
    y = np.zeros_like(x)
    y = x + v

end_time = time.time()
print(end_time-start_time)

2.3251209259033203


# Exercise on Matrix Multiplication

In [101]:
import numpy as np
import time
def normal_multiply(A1, A2):
    B = [list(range(len(A1))) for _ in range(len(A2[0]))]
    for a1_r in range(len(A1)):
        for a2_c in range(len(A2[0])):
            res = 0
            for a2_r in range(len(A2)):
                res += A1[a1_r][a2_r] * A2[a2_r][a2_c]
            B[a1_r][a2_c] = res

    return B

def numpy_multiply(A1, A2):
    A1n = np.array(A1)
    A2n = np.array(A2)

    return np.dot(A1n,A2n)

A1 = (np.random.random((50,40)) * 100).astype(np.int)
A2 = (np.random.random((40,50)) * 100).astype(np.int)

assert(np.sum(normal_multiply(A1, A2) != numpy_multiply(A1, A2)) == 0)

start_time = time.time()
for i in range(100):
    normal_multiply(A1, A2)
end_time = time.time()
normal_multiply_time = end_time - start_time

start_time = time.time()
for i in range(100):
    numpy_multiply(A1, A2)
end_time = time.time()
numpy_multiply_time = end_time - start_time

print("Normal multiply time: %0.4f"%(normal_multiply_time))
print("Numpy multiply time: %0.4f"%(numpy_multiply_time))
print("Speed up: %dx"%(normal_multiply_time/numpy_multiply_time))

Normal multiply time: 5.9400
Numpy multiply time: 0.0065
Speed up: 911x


In [102]:
a = np.random.random((5,2))
print(a)

[[ 0.95271567  0.23115616]
 [ 0.49627075  0.67414702]
 [ 0.89698948  0.9482825 ]
 [ 0.82208556  0.19245972]
 [ 0.26974855  0.52257125]]


In [103]:
list(a)

[array([ 0.95271567,  0.23115616]),
 array([ 0.49627075,  0.67414702]),
 array([ 0.89698948,  0.9482825 ]),
 array([ 0.82208556,  0.19245972]),
 array([ 0.26974855,  0.52257125])]

In [104]:
v = np.random.random((5,))

In [105]:
print(list(v))

[0.91984180031922902, 0.089264307036450163, 0.0545681232317623, 0.45620955828195586, 0.11446009654372968]
